### ISSUE TITLE
With alignAttributes set to true, format document doesn't align attributes

### ISSUE THREAD

**Issue by danschultequb** [danschultequb/qub-typescript-xml-vscode#7]
If I have a document with the following contents:
```xml
    <sometag firstattr=""
    second="" />
```
And then I try to format the document with alignAttributes set to true, I would expect the result to be this:
```xml
    <sometag firstattr=""
             second="" />
```
Currently it doesn't respect alignAttributes, though, and results in this:
```xml
    <sometag firstattr=""
        second="" />
```
I have [a few tests](https://github.com/danschultequb/qub-typescript-xml/blob/master/tests/xml.tests.ts#L3753) in my xml parser repository that show that this scenario works outside of the current VS Code extension.
See [James Fancy's review from Augutst 1, 2017](https://marketplace.visualstudio.com/items?itemName=qub.qub-xml-vscode#review-details) for the origin of this issue.

**Comment by danschultequb** [comment]
This happened because I changed the name of the extension recently ("qub-xml" to "qub-xml-vscode") but I forgot to change the names of the settings associated with the extension. To fix this problem, just make sure your alignAttributes setting is set using:
```json
"qub-xml-vscode.formatOptions.alignAttributes": true
```
I also recommend updating to the latest version (1.2.5) too.

**Comment by jamesfancy** [comment]
@danschultequb I reinstalled the extentions and re-set `qub-xml-vscode.formatOptions.alignAttributes` to `true`. The issue is still there.

![image](https://user-images.githubusercontent.com/3953094/29250046-0d788ec8-806e-11e7-82f1-9dca1952b727.png)

![image](https://user-images.githubusercontent.com/3953094/29250052-2184375a-806e-11e7-8c4f-84e14b47f6ad.png)

So, what's different between us and what does cause the different representation.

**Comment by danschultequb** [comment]
@jamesfancy I just tested this on my machine with version 1.2.6, and it seems to work fine. If you're still having issues, please send me a sample of XML that is giving you problems.

**Comment by jamesfancy** [comment]
@danschultequb It's ok now, thank you. Perhaps I met the problem since vscode didn't restart after the plugin updated.
